import localFont from "next/font/local";
import { Montserrat } from "@next/font/google"; // Import Montserrat
import "./globals.css";

// Local Fonts
const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});

const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

// Montserrat Font
const montserrat = Montserrat({
  subsets: ["latin"], // Load Latin subset
  variable: "--font-montserrat", // Define a custom variable for Montserrat
  weight: ["400", "700"], // Load specific weights
});

// Metadata
export const metadata = {
  title: "SuuaveFTX",
  description: "Generated by create next app",
};

// Root Layout Component
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${montserrat.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
