export const ongoingContracts = [
    {
        id: '24t64754',
        title: 'Modern Fashion Attire Illustration',
        status: 'Waiting Approval',
        startDate: '18th June, 2024',
        endDate: '25th June, 2024',
        isLate: false,
        daysLate: null,
        isSubmitted: true,
        budget: "₦200,000",
        timeframe: "7 Days",
        artist: {
            name: 'Aliu',
            username: 'aliu',
            role: 'Fashion Artist',
            location: 'Lagos, Nigeria',
            rating: 0.0,
            reviews: 0,
            avatar: '/contract/designer.jpg',
        },
    },
    {
        id: '24t64755',
        title: 'Modern Fashion Attire Illustration',
        startDate: '18th June, 2024',
        endDate: '25th June, 2024',
        isLate: true,
        daysLate: '10',
        status: 'Ongoing',
        isSubmitted: false,
        budget: "₦200,000",
        timeframe: "7 Days",
        artist: {
            name: 'Adeniji',
            username: 'adeniji',
            role: 'Fashion Artist',
            location: 'Lagos, Nigeria',
            rating: 0.0,
            reviews: 0,
            avatar: '/contract/designer.jpg',
        },
    },
    {
        id: '24t64756',
        title: 'Modern Fashion Attire Illustration',
        startDate: '18th June, 2024',
        endDate: '25th June, 2024',
        isLate: false,
        isExpiringSoon: true,
        remainingDays: '5',
        status: 'Ongoing',
        isSubmitted: false,
        budget: "₦200,000",
        timeframe: "7 Days",
        artist: {
            name: 'Adeniji',
            username: 'adeniji',
            role: 'Fashion Artist',
            location: 'Lagos, Nigeria',
            rating: 0.0,
            reviews: 0,
            avatar: '/contract/designer.jpg',
        },
    },
    {
        id: '24t64757',
        title: 'Modern Fashion Attire Illustration',
        startDate: '18th June, 2024',
        endDate: '25th June, 2024',
        isLate: true,
        daysLate: '10',
        status: 'Ongoing',
        isSubmitted: false,
        budget: "₦200,000",
        timeframe: "7 Days",
        artist: {
            name: 'Adeniji',
            username: 'adeniji',
            role: 'Fashion Artist',
            location: 'Lagos, Nigeria',
            rating: 0.0,
            reviews: 0,
            avatar: '/contract/designer.jpg',
        },
    },
    {
        id: '24t64758',
        title: 'Modern Fashion Attire Illustration',
        startDate: '18th June, 2024',
        endDate: '25th June, 2024',
        isLate: true,
        daysLate: '10',
        status: 'Ongoing',
        isSubmitted: false,
        budget: "₦200,000",
        timeframe: "7 Days",
        artist: {
            name: 'Adeniji',
            username: 'adeniji',
            role: 'Fashion Artist',
            location: 'Lagos, Nigeria',
            rating: 0.0,
            reviews: 0,
            avatar: '/contract/designer.jpg',
        },
    },
];
