import * as React from "react";

import "./globals.css";
import CustomNavbar from "../components/Navbar";

// Metadata
export const metadata = {
  title: "SuuaveFTX",
  description: "Generated by create next app",
};

// Root Layout Component
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`font-proximanova`}>{children}</body>
    </html>
  );
}
