
export const collectionData = [
  {
    id: 1,
    url: "/collectionImage/image-1.svg",
    title: " New Men Africa Collection",
    details: {
      images: [
        "/collectionImage/image-1.svg",
        "/collectionImage/image-1.svg",
        "/collectionImage/image-1.svg",
      ],
      title: "Modern Nigerian Agbada with Traditional Embellishments",
      collectionFiles: ["DC15263UG", "DC15263UG"],
      type: "Exclusive",
      artist: {
        name: "Ocean Watermelon",
        username: "ocean",
        image: "/collectionImage/image-6.svg",
      },
      price: "$100,000",
      purchaseDate: "2nd November, 2024",
    },
  },
  {
    id: 2,
    url: "/collectionImage/image-2.svg",
    title: " New Men Africa Collection",
    details: {
      images: [
        "/collectionImage/image-2.svg",
        "/collectionImage/image-2.svg",
        "/collectionImage/image-2.svg",
      ],
      title: "Modern Nigerian Agbada with Traditional Embellishments",
      collectionFiles: ["DC15263UG", "DC15263UG"],
      type: "Exclusive",
      artist: {
        name: "Ocean Watermelon",
        image: "/collectionImage/image-6.svg",
      },
      price: "$420,000",
      purchaseDate: "2nd November, 2024",
    },
  },
  {
    id: 3,
    url: "/collectionImage/image-3.svg",
    title: " New Men Africa Collection",
    details: {
      images: [
        "/collectionImage/image-3.svg",
        "/collectionImage/image-3.svg",
        "/collectionImage/image-3.svg",
      ],
      title: "Modern Nigerian Agbada with Traditional Embellishments",
      collectionFiles: ["DC15263UG", "DC15263UG"],
      type: "Exclusive",
      artist: {
        name: "Ocean Watermelon",
        image: "/collectionImage/image-6.svg",
      },
      price: "$10,000",
      purchaseDate: "2nd November, 2024",
    },
  },
  {
    id: 4,
    url: "/collectionImage/image-4.svg",
    title: " New Men Africa Collection",
    details: {
      images: [
        "/collectionImage/image-4.svg",
        "/collectionImage/image-4.svg",
        "/collectionImage/image-4.svg",
      ],
      title: "Modern Nigerian Agbada with Traditional Embellishments",
      collectionFiles: ["DC15263UG", "DC15263UG"],
      type: "Non-Exclusive",
      artist: {
        name: "Ocean Watermelon",
        image: "/collectionImage/image-6.svg",
      },
      price: "$200,000",
      purchaseDate: "2nd November, 2024",
    },
  },
  {
    id: 5,
    url: "/collectionImage/image-5.svg",
    title: " New Men Africa Collection",
    details: {
      images: [
        "/collectionImage/image-5.svg",
        "/collectionImage/image-5.svg",
        "/collectionImage/image-5.svg",
      ],
      title: "Modern Nigerian Agbada with Traditional Embellishments",
      collectionFiles: ["DC15263UG", "DC15263UG"],
      type: "Non-Exclusive",
      artist: {
        name: "Ocean Watermelon",
        image: "/collectionImage/image-6.svg",
      },
      price: "$200,000",
      purchaseDate: "2nd November, 2024",
    },
  },
  {
    id: 6,
    url: "/collectionImage/image-1.svg",
    title: " New Men Africa Collection",
    details: {
      images: [
        "/collectionImage/image-1.svg",
        "/collectionImage/image-1.svg",
        "/collectionImage/image-1.svg",
      ],
      title: "Modern Nigerian Agbada with Traditional Embellishments",
      collectionFiles: ["DC15263UG", "DC15263UG"],
      type: "Non-Exclusive",
      artist: {
        name: "Ocean Watermelon",
        image: "/collectionImage/image-6.svg",
      },
      price: "$200,000",
      purchaseDate: "2nd November, 2024",
    },
  },
  {
    id: 7,
    url: "/collectionImage/image-2.svg",
    title: " New Men Africa Collection",
    details: {
      images: [
        "/collectionImage/image-2.svg",
        "/collectionImage/image-2.svg",
        "/collectionImage/image-2.svg",
      ],
      title: "Modern Nigerian Agbada with Traditional Embellishments",
      collectionFiles: ["DC15263UG", "DC15263UG"],
      type: "Non-Exclusive",
      artist: {
        name: "Ocean Watermelon",
        image: "/collectionImage/image-6.svg",
      },
      price: "$200,000",
      purchaseDate: "2nd November, 2024",
    },
  },
  {
    id: 8,
    url: "/collectionImage/image-3.svg",
    title: "African Heritage Collection",
    details: {
      images: ["/collectionImage/image-3.svg"],
      title: "Modern Nigerian Agbada with Traditional Embellishments",
      collectionFiles: ["DC15263UG"],
      type: "Exclusive",
      artist: { name: "Ocean Watermelon", image: "/collectionImage/image-6.svg" },
      price: "$85,000",
      purchaseDate: "5th November, 2024",
    },
  },
  {
    id: 9,
    url: "/collectionImage/image-4.svg",
    title: "Kente Royale Collection",
    details: {
      images: ["/collectionImage/image-4.svg"],
      title: "Modern Nigerian Agbada with Traditional Embellishments",
      collectionFiles: ["DC15263UG"],
      type: "Non-Exclusive",
      artist: { name: "Ocean Watermelon", image: "/collectionImage/image-6.svg" },
      price: "$55,000",
      purchaseDate: "8th November, 2024",
    },
  },
  {
    id: 10,
    url: "/collectionImage/image-5.svg",
    title: "Lagos Street Wear",
    details: {
      images: ["/collectionImage/image-5.svg"],
      title: "Modern Nigerian Agbada with Traditional Embellishments",
      collectionFiles: ["DC15263UG"],
      type: "Exclusive",
      artist: { name: "Ocean Watermelon", image: "/collectionImage/image-6.svg" },
      price: "$310,000",
      purchaseDate: "12th November, 2024",
    },
  },
  {
    id: 11,
    url: "/collectionImage/image-1.svg",
    title: "Ankara Modern Fusion",
    details: {
      images: ["/collectionImage/image-1.svg"],
      title: "Modern Nigerian Agbada with Traditional Embellishments",
      collectionFiles: ["DC15263UG"],
      type: "Non-Exclusive",
      artist: { name: "Ocean Watermelon", image: "/collectionImage/image-6.svg" },
      price: "$75,000",
      purchaseDate: "15th November, 2024",
    },
  },
  {
    id: 12,
    url: "/collectionImage/image-2.svg",
    title: "Aso-Oke Couture Line",
    details: {
      images: ["/collectionImage/image-2.svg"],
      title: "Modern Nigerian Agbada with Traditional Embellishments",
      collectionFiles: ["DC15263UG"],
      type: "Exclusive",
      artist: { name: "Ocean Watermelon", image: "/collectionImage/image-6.svg" },
      price: "$140,000",
      purchaseDate: "20th November, 2024",
    },
  },
];
